name: CArtCore
version: '${version}'
main: moe.muska.ami.spcraft.cartcore.CArtCore
api-version: '1.19'
authors: [ Muska_Ami ]
description: SPCraftMC 2.0 CloudArt Core
loader: moe.muska.ami.spcraft.cartcore.CArtCoreLoader
dependencies:
  server:
    PlaceholderAPI:
      load: AFTER
      required: false
    Vault:
      load: AFTER
      required: false
permissions:
  cartcore.*:
    default: false
    description: CArtCore all permission
    children:
      cartcore.command.reload:
        default: op
        description: CArtCore reload command permission
      cartcore.command.warp:
        default: op
        description: CArtCore warp command permission