name: CArtCore
version: '${version}'
main: moe.muska.ami.spcraft.cartcore.CArtCore
api-version: '1.19'
authors: [ Muska_Ami ]
description: SPCraftMC 2.0 CloudArt Core
dependencies:
  server:
    PlaceholderAPI:
      load: AFTER
      required: false
commands:
  cartcore:
    description: CArtCore commands
    usage: /cartcore <args>
  cac:
    description: CArtCore commands
    usage: /cac <args>
permissions:
  cartcore.*:
    default: false
    description: CArtCore all permission
    children:
      cartcore.command.reload:
        default: op
        description: CArtCore reload command permission