# 低耐久保护
damage-protection:
  # 开关
  enable: true
  # 工具剩余多少耐久不再触发连锁
  value: 10

# 忽略附魔
ignore-enchant: false

# 树木连锁
tree:
  # 开关
  enable: false
  # 连锁树叶（消耗耐久）
  leave: false
  # 创造模式下开启此功能
  creative-mode-support: false
  map:
    # 可连锁的原木
    logs:
      - "WARPED_STEM"
      - "CRIMSON_STEM"
      - "OAK_LOG"
      - "BIRCH_LOG"
      - "SPRUCE_LOG"
      - "JUNGLE_LOG"
      - "DARK_OAK_LOG"
      - "ACACIA_LOG"
      - "MANGROVE_ROOTS"
      - "MANGROVE_LOG"
      - "CHERRY_LOG"
    # 可连锁的树叶
    leaves:
      - "NETHER_WART_BLOCK"
      - "WARPED_WART_BLOCK"
      - "OAK_LEAVES"
      - "BIRCH_LEAVES"
      - "SPRUCE_LEAVES"
      - "JUNGLE_LEAVES"
      - "DARK_OAK_LEAVES"
      - "ACACIA_LEAVES"
      - "MANGROVE_LEAVES"
      - "CHERRY_LEAVES"
    # 可用于连锁采集树木的工具
    tools:
      - "NETHERITE_AXE"
      - "DIAMOND_AXE"
      - "GOLDEN_AXE"
      - "IRON_AXE"
      - "STONE_AXE"
      - "WOODEN_AXE"

# 矿石连锁
ore:
  # 开关
  enable: false
  # 创造模式下开启此功能
  creative-mode-support: false
  map:
    # 可连锁的矿石
    ores:
      - "COAL_ORE"
      - "COPPER_ORE"
      - "LAPIS_ORE"
      - "IRON_ORE"
      - "GOLD_ORE"
      - "REDSTONE_ORE"
      - "DIAMOND_ORE"
      - "EMERALD_ORE"
      - "DEEPSLATE_COAL_ORE"
      - "DEEPSLATE_COPPER_ORE"
      - "DEEPSLATE_LAPIS_ORE"
      - "DEEPSLATE_IRON_ORE"
      - "DEEPSLATE_GOLD_ORE"
      - "DEEPSLATE_REDSTONE_ORE"
      - "DEEPSLATE_DIAMOND_ORE"
      - "DEEPSLATE_EMERALD_ORE"
      - "NETHER_GOLD_ORE"
      - "NETHER_QUARTZ_ORE"
    # 可用于连锁采集矿石的工具
    tools:
      - "NETHERITE_PICKAXE"
      - "DIAMOND_PICKAXE"
      - "GOLDEN_PICKAXE"
      - "IRON_PICKAXE"
      - "STONE_PICKAXE"
      - "WOODEN_PICKAXE"

# 挖掘方块获得的经验
experience:
  # 可自行添加，e.g.
  # OAK_LEAVES:
  #   items:
  #     - "OAK_LEAVES"
  #   min: 0
  #   max: 1
  COAL:
    items:
      - "COAL_ORE"
      - "DEEPSLATE_COAL_ORE"
    min: 0
    max: 2
  LAPIS:
    items:
      - "LAPIS_ORE"
      - "DEEPSLATE_LAPIS_ORE"
    min: 2
    max: 5
  REDSTONE:
    items:
      - "REDSTONE_ORE"
      - "DEEPSLATE_REDSTONE_ORE"
    min: 1
    max: 5
  DIAMOND:
    items:
      - "DIAMOND_ORE"
      - "DEEPSLATE_DIAMOND_ORE"
    min: 3
    max: 7
  EMERALD:
    items:
      - "EMERALD_ORE"
      - "DEEPSLATE_EMERALD_ORE"
    min: 3
    max: 7
  NETHER_QUARTZ:
    items:
      - "NETHER_QUARTZ_ORE"
    min: 2
    max: 5
  NETHER_GOLD:
    items:
      - "NETHER_GOLD_ORE"
    min: 0
    max: 1